version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: graphql-server
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432"
  web:
    image: typescript-node-gql-server
    depends_on:
      - db
    ports:
      - "4000:4000"
    # command: sh -c "npm install && npm run dev"